apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: react-app-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/YOGESHnp/air-max-270-gitops.git
    targetRevision: main
    path: apps/react-app/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated: { prune: true, selfHeal: true }
    syncOptions: [CreateNamespace=true]
